/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddToPlaylistDialog: typeof import('./components/Playlist/AddToPlaylistDialog.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    CardTitle: typeof import('./components/ui/CardTitle.vue')['default']
    Header: typeof import('./components/Layout/Header.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    LazyImage: typeof import('./components/ui/LazyImage.vue')['default']
    LoginDialog: typeof import('./components/Layout/LoginDialog.vue')['default']
    MainLayout: typeof import('./components/Layout/MainLayout.vue')['default']
    PlayerBar: typeof import('./components/Layout/PlayerBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Layout/Sidebar.vue')['default']
  }
}
